@URL = http://localhost:3000/api
@json = content-type: application/json
###
GET {{URL}}

### 注册
POST {{URL}}/register
{{json}}

{  
  "username": "pdeng",
  "password": "123123"
}

### 登录
POST {{URL}}/login
{{json}}

{  
  "username": "pdeng",
  "password": "123123"
}

### 获取用户列表
GET {{URL}}/users

### 获取个人信息
GET {{URL}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNGQ1OWJlMDMzOGQwMTMzY2ZmZjU1YyIsImlhdCI6MTU4MjEyODQ3OH0.RjDiermuV7clQWENSXgXVBbiOiamiFbbE2I4hO91TGw
