@URL = http://localhost:3000/api
@json = content-type: application/json
###
GET http://localhost:3000

### 注册
POST {{URL}}/register
{{json}}

{  
  "username": "pdeng",
  "password": "123123"
}

### 登录
POST {{URL}}/login
{{json}}

{  
  "username": "pdeng",
  "password": "123123"
}

### 获取用户列表
GET {{URL}}/users

### 获取个人信息
GET {{URL}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNGY4NjcxNTBkODYxOTE3N2NlYjY2MCIsImlhdCI6MTU4MjI3MDI4NH0.iqOg3JxF-JomtTBb0WBKYRhfh7k3G0T7O7HU5xph-ck
